Michael improve user controller api param documentation
ucsb-cs156-s23/proj-gauchoride-s23-5pm-4 pull request #25
Opened 2023-05-28 23:24 UTC by mike-k999

In this PR we add more information into the @APIParam fields in the UserController so better documentation appears in Swagger.  It is based from PR #23, which in turn is based on PR #22, so merge in order.  Closes #24

2023-05-30 20:18 UTC, SophiaWeiler submitted a review, later dismissed
Looks good!

2023-05-30 20:25 UTC, strongani approved these changes, later dismissed
Looks good, nice that you did it for both toggling Admin and Driver!

2023-05-31 05:58 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    const toggleDriverCallback = async (cell) => { toggleDriverMutation.mutate(cell); }
The description of this PR says that it makes changes to the backend—but these are front end changes.

Is this a mistake, or does the description need to be updated?

Here's what is says right now:
> In this PR we add more information into the @APIParam fields in the UserController so better documentation appears in Swagger. It is based from PR https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/pull/23, which in turn is based on PR https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/pull/22, so merge in order. Closes https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/issues/24

2023-05-31 06:01 UTC, pconrad requested changes
The backend code all looks good to me.  But there are also frontend changes in the PR, which doesn't match the description; so I want to be sure that this was intentional.


If it was: please update the description (including a description of what changed in the UX, along with storybook links and screenshots).

If it wasn't: then proceed accordingly.

2023-05-31 18:10 UTC, mike-k999 commented on frontend/src/main/components/Users/UsersTable.js
> +    const toggleDriverCallback = async (cell) => { toggleDriverMutation.mutate(cell); }
> Is this a mistake, or does the description need to be updated?

Right.  So I think what has happened here is that this branch is based at the one from PR #23, which is where the frontend changes occurred.  I probably didn't indicate that in the proper way but I tried to include that in the comment.  The only changes different from this PR and PR #23 are backend changes; I thought once the others were merged to main it would only show the changes that are new, although clearly this is not the case.

What would you like me to do in this case?

2023-06-01 01:22 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    const toggleDriverCallback = async (cell) => { toggleDriverMutation.mutate(cell); }
If the other changes have already been merged to main, then maybe rebasing on main will fix things?

Or we can do some git surgery with git cherry-pick and git reset to turn this branch into one that just has the backend changes.

2023-06-01 01:28 UTC, pconrad approved these changes

2023-06-01 01:32 UTC, zachmiller-ucsb approved these changes
LGTM

2023-06-01 01:38 UTC, merged