driver shift table frontend
ucsb-cs156-s23/proj-gauchoride-s23-5pm-4 pull request #26
Opened 2023-05-30 21:35 UTC by ru1nw

In this PR, I added a frontend webpage for driver shift table.

2023-06-01 01:37 UTC, pconrad commented
@ru1nw Ian, see my comments on the slack with suggestions about how to overcome the test failures...

https://ucsb-cs156-s23.slack.com/archives/C0515SM2Z5M/p1685583124776489

2023-06-01 23:32 UTC, SophiaWeiler requested changes
I think that this should have been broken down into multiple PRs, the first being the component for the table + tests + storybook (which is missing, you need to include the link to this in your PR) and then the second being the page with the link in Navbar. Can you update the description for the PR so that we can get a sense of what is being changed here?

2023-06-02 17:45 UTC, pconrad requested changes
A few things to address

2023-06-02 17:45 UTC, pconrad commented on frontend/src/main/components/Shift/ShiftTable.js
> +    // Stryker enable all
Please change to `// Stryker restore all`

See: https://ucsb-cs156-s23.slack.com/archives/C050779M19P/p1685726928710669

2023-06-02 17:45 UTC, pconrad commented on frontend/src/main/pages/ShiftPage.js
> +            {/* <h2>Shift</h2> */}
Can we remove this commented out line?

2023-06-04 03:05 UTC, ru1nw commented
Closing this PR due to the large amount of files being changed. Will move to other branches so create smaller PRs.

2023-06-04 03:05 UTC, closed without merging