Sophia - updating currentUserFixtures to mock ROLE_DRIVER
ucsb-cs156-s23/proj-gauchoride-s23-5pm-4 pull request #31
Opened 2023-05-31 19:26 UTC by SophiaWeiler

In this PR, I am updating the currentUserFixtures to include the "driver" tag as it has in the backend and adding a new type of user "driver" that has a "ROLE_DRIVER" so that I can test and mock in the frontend while the backend is being developed.

2023-06-01 01:10 UTC, strongani reviewed
Do we assume that an Admin is also a Driver (or has permission of a driver)? Also, in the case I believe that for adminUser, there should be a role `"authority": "ROLE_DRIVER"` in the roles array.

2023-06-01 17:00 UTC, SophiaWeiler commented
> Do we assume that an Admin is also a Driver (or has permission of a driver)? Also, in the case I believe that for adminUser, there should be a role `"authority": "ROLE_DRIVER"` in the roles array and in the roles list at the end of the file.

You are right, I will add the ROLE_DRIVER authority to the admin as well

2023-06-01 22:05 UTC, strongani requested changes

2023-06-01 22:05 UTC, strongani commented on frontend/src/fixtures/currentUserFixtures.js
On currentUserFixtures at the bottom, add ROLE_DRIVER to adminUser

2023-06-01 22:34 UTC, strongani approved these changes
LGTM

2023-06-02 17:22 UTC, pconrad approved these changes
LGTM

2023-06-02 17:22 UTC, merged