Sophia - add Rider Create Page
ucsb-cs156-s23/proj-gauchoride-s23-5pm-4 pull request #36
Opened 2023-06-01 22:15 UTC by SophiaWeiler

In this PR, I have created a new page to create a new ride request called RiderCreatePage. It also has tests and a storybook component (which I have included a small screen shot below to document what the page will look like).

<img width="1412" alt="Screen Shot 2023-06-01 at 3 13 46 PM" src="https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-4/assets/44530739/86d1dcfe-f33c-4e49-adfd-d9598bb0a20a">

2023-06-04 20:37 UTC, zachmiller-ucsb approved these changes, later dismissed
LGTM - checked code quality + storybook entry

2023-06-04 23:22 UTC, mike-k999 submitted a review, later dismissed
lgtm

2023-06-05 01:48 UTC, pconrad requested changes
naming, naming, naming....

2023-06-05 01:48 UTC, pconrad commented on frontend/src/main/pages/Rider/RiderCreatePage.js
> +export default function RiderCreatePage() {
Can we call this a name that matches what the user see and thinks of this as?
```suggestion
export default function RideRequestCreatePage() {
```

I've had a lot of experience with code bases where names in the code are out of alignment with what the  user thinks and sees. Everyone hates working in those code bases.  The best time to fix it is before it goes into the main branch.

2023-06-05 01:48 UTC, pconrad commented on frontend/src/stories/pages/Rider/RiderCreatePage.stories.js
> +import RiderCreatePage from 'main/pages/Rider/RiderCreatePage';
```suggestion
import RideRequestCreatePage from 'main/pages/RideRequest/RideRequestCreatePage';
```

2023-06-05 01:48 UTC, pconrad commented on frontend/src/stories/pages/Rider/RiderCreatePage.stories.js
> +    title: 'pages/Rider/RiderCreatePage',
You can guess what I want here

2023-06-05 01:48 UTC, pconrad commented on frontend/src/tests/pages/Rider/RiderCreatePage.test.js
> +import { render, waitFor, fireEvent } from "@testing-library/react";
Please do an incremental global search / replace one at a time on `Rider` and see for each one, whether it should be `RideRequest`.

Also: what's in the backend?  Is it Rider?  or RideRequest?  Do we need to fix it there also?

2023-06-06 18:09 UTC, mike-k999 reviewed
Looks like zach changed "rider" --> "rideRequest", while in the previous PR I had changed "rider" --> "ride".  This is most likely the merge conflict and personally I feel just using "ride" would be shorter and simpler.

2023-06-06 20:43 UTC, strongani approved these changes
LGTM!

2023-06-06 21:22 UTC, mike-k999 approved these changes
Ok so all pages are "RideRequest" and form is just "Ride".  We will remember this convention in this case.

2023-06-08 00:01 UTC, pconrad approved these changes
LGTM

2023-06-08 00:02 UTC, merged