Sophia - adding rider edit page
ucsb-cs156-s23/proj-gauchoride-s23-5pm-4 pull request #38
Opened 2023-06-02 23:25 UTC by SophiaWeiler

2023-06-04 20:43 UTC, zachmiller-ucsb requested changes
I can only see the rider create page in storybook?

2023-06-04 20:46 UTC, SophiaWeiler commented
> I can only see the rider create page in storybook?

I made a note about this in the PR description, because it takes input from the backend, it doesn't render a storybook page properly. This was also the case for team03, but when deployed with a functioning backend, it rendered as expected.

2023-06-05 01:43 UTC, mike-k999 commented
> 

I think Sophia is correct, I see the form on storybook at least.

2023-06-05 01:52 UTC, zachmiller-ucsb requested changes, later dismissed
Michael and I tried to test locally and it wasn't working for us. Maybe tomorrow or Tuesday we can rework things

2023-06-05 01:56 UTC, pconrad requested changes
Please check the naming... a lot of things that have `Rider` on them should probably have `RideRequest` on them.

A `Rider` is a person.  We would expect a  `RiderForm` to be a form for entering information about a person, not about a Ride.    For that we want a `RideForm` or a `RideRequestForm`.

2023-06-05 17:56 UTC, SophiaWeiler commented
> Michael and I tried to test locally and it wasn't working for us. Maybe tomorrow or Tuesday we can rework things

I think it is because we don't have a working backend so there is nothing to GET from.

2023-06-06 21:25 UTC, strongani requested changes, later dismissed
Remove riderId parameter from api requests.

2023-06-06 21:25 UTC, strongani commented on frontend/src/main/pages/Ride/RideRequestEditPage.js
> +        riderId: ride.riderId,
Put for backend does not require riderId, automatically fills it in. So, it should not have riderId in params. Also for tests.

2023-06-06 22:22 UTC, mike-k999 approved these changes, later dismissed
lgtm

2023-06-08 00:56 UTC, pconrad approved these changes

2023-06-08 00:56 UTC, merged