Zach - Toggle Role on Users Page Login Bug
ucsb-cs156-s23/proj-gauchoride-s23-5pm-4 pull request #43
Opened 2023-06-04 18:40 UTC by zachmiller-ucsb

Closes #3

2023-06-05 01:41 UTC, mike-k999 approved these changes
lgtm

2023-06-05 02:01 UTC, pconrad requested changes
Could you take a look at whether the ShiftRepository.java change is supposed to be in this PR?

2023-06-05 02:01 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/repositories/ShiftRepository.java
> +  Optional<Shift> findByDriverID(Long driverID);
Is this change supposed to be in this PR?

It seems unrelated...

2023-06-05 02:03 UTC, zachmiller-ucsb commented
This was also patching an issue with main causing gh actions to fail on this commit @pconrad . I can make that clear in the commit message

2023-06-06 04:56 UTC, SophiaWeiler approved these changes
lgtm

2023-06-06 16:43 UTC, pconrad approved these changes
lgtm!

2023-06-06 16:44 UTC, merged