Ameymwalimbe shift get post
ucsb-cs156-s23/proj-gauchoride-s23-5pm-4 pull request #56
Opened 2023-06-06 22:01 UTC by ameymwalimbe

In this PR, I add the backend Post and Get functionality to the shift table in #8. Michael helped me with the Post tests, and it works on Swagger. From this, drivers should be able to add their ride shifts, and any user can get all ride shifts. The shiftStart and end parameters in shift entity has been changed to type String instead of LocalTime, as I was unable to test on LocalTime objects in Swagger.

2023-06-06 22:12 UTC, mike-k999 submitted a review, later dismissed
LGTM.  We will need to check at the time of the api call that the time strings match format @ru1nw

2023-06-06 22:21 UTC, zachmiller-ucsb submitted a review, later dismissed
Format Api documentation in Swagger to make it clear what the format of post endpoint attributes need to be. For example, the days needs to be Monday, Tuesday, Wednesday, etc which was unclear. Also, the times work when it is something like 10:30 for POST, but not 10:30am or 10:30AM despite swagger saying the attribute should just be type string

2023-06-08 00:36 UTC, strongani requested changes
change tests as necessary?

2023-06-08 00:36 UTC, strongani commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/ShiftController.java
> +    @PreAuthorize("hasRole('ROLE_DRIVER')")
Maybe Admins should also be able to make a new shift.

2023-06-08 00:58 UTC, strongani approved these changes
LGTM!

2023-06-08 03:06 UTC, pconrad approved these changes
LGTM

2023-06-08 03:07 UTC, merged