Anikait ride add student
ucsb-cs156-s23/proj-gauchoride-s23-5pm-4 pull request #60
Opened 2023-06-08 22:21 UTC by strongani

In this PR, we added the `student` attribute to the Ride entity, and the Ride controller get, so that the Student name could be seen in the RideTable on the frontend. Also fixed a bug with the path of the Create Ride button.

2023-06-08 22:27 UTC, SophiaWeiler approved these changes, later dismissed
lgtm

2023-06-09 20:50 UTC, pconrad approved these changes
LGTM--will test on staff qa

2023-06-09 21:38 UTC, pconrad requested changes
Currently, the edit button from the RideRequest page leads to a blank page, because the url

`https://proj-gauchoride-staff-qa.dokku-04.cs.ucsb.edu/ride/edit/2`

has no mapping in App.js. But if you manually edit the url to this:

`https://proj-gauchoride-staff-qa.dokku-04.cs.ucsb.edu/ride/edit2`

then it works.

So I think you need a one character change to fix this.  This is type of error that you find with end2end testing (which we don't have in our stack yet.)  In the meantime, it only shows up with manual testing.

2023-06-09 21:38 UTC, pconrad commented on frontend/src/App.js
> +          (hasRole(currentUser, "ROLE_ADMIN")  || hasRole(currentUser, "ROLE_RIDER") )&& <Route exact path="/ride/edit:id" element={<RideRequestEditPage />} />
I think this change will fix the bug where the edit button doesn't work:

```suggestion
          (hasRole(currentUser, "ROLE_ADMIN")  || hasRole(currentUser, "ROLE_RIDER") )&& <Route exact path="/ride/edit/:id" element={<RideRequestEditPage />} />
```

2023-06-09 22:09 UTC, merged